# Generated by Django 3.2.5 on 2022-10-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('T', 'Todo'), ('D', 'Done'), ('C', 'Canceled')], default='T', max_length=1)),
                ('priority', models.CharField(choices=[('S', 'S-Rank'), ('A', 'A-Rank'), ('B', 'B-Rank')], default='S', max_length=1)),
            ],
        ),
    ]
